### ISSUE TITLE
Não permitir cadastrar repasses com datas concomitantes

### ISSUE THREAD

**Issue by r-matias** [prefeiturasp/sme-ptrf#3]
Como usuário do sistema, ao cadastrar um programa com vários repasses, não devo conseguir utilizar as mesmas datas de vigência em mais de um repasse. Deste modo, para conseguir cadastrar mais de um repasse por programa, o sistema deverá validar as datas de vigência dos repasses, permitindo o cadastro apenas de repasses que ocorram em períodos diferentes. Bloqueando o cadastro de repasses com datas concomitantes.
Não permitir datas concomitantes entre repasses: validar dados em memória cadastrados no front-end, validar back-end no momento de salvar. Testar cadastro de programas.

![periodos padrao do ptrf](https://cloud.githubusercontent.com/assets/25390861/22835193/0c4f781e-ef9f-11e6-8ad9-453f80613070.jpg)

**Comment by alinedornelas** [comment]
Item aceito.
